# Generated by Django 3.1.7 on 2021-03-24 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stories', models.SmallIntegerField(null=True, verbose_name='Этажность')),
                ('lng', models.FloatField(verbose_name='Долгота')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('year', models.DateField(verbose_name='Год постройки')),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.SmallIntegerField(null=True, verbose_name='Этаж')),
                ('rooms', models.SmallIntegerField(null=True, verbose_name='Количество комнат')),
                ('price', models.FloatField(verbose_name='Цена общая')),
                ('area', models.FloatField(verbose_name='Площадь')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.building', verbose_name='Адрес')),
            ],
        ),
    ]
