# Generated by Django 3.1.7 on 2021-03-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='year',
            field=models.SmallIntegerField(verbose_name='Год постройки'),
        ),
    ]
