# Generated by Django 3.1.7 on 2021-03-24 07:40

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210324_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='lat',
            field=models.FloatField(validators=[main.models.validate_lat], verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='building',
            name='lng',
            field=models.FloatField(validators=[main.models.validate_lng], verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='building',
            name='year',
            field=models.SmallIntegerField(null=True, verbose_name='Год постройки'),
        ),
    ]
