# Generated by Django 3.1.7 on 2021-03-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210324_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='stories',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Этажность'),
        ),
        migrations.AlterField(
            model_name='building',
            name='year',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Год постройки'),
        ),
    ]
