# Generated by Django 3.1.7 on 2021-03-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210324_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='stories',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Этажность'),
        ),
        migrations.AlterField(
            model_name='building',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год постройки'),
        ),
    ]
