# Generated by Django 3.1.7 on 2021-03-26 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_building_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='number',
            field=models.PositiveSmallIntegerField(default=0, verbose_name=''),
        ),
        migrations.AddField(
            model_name='building',
            name='street',
            field=models.CharField(default='', max_length=200, verbose_name=''),
        ),
    ]
