# Generated by Django 3.1.7 on 2021-03-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210326_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='number',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Номер квартиры'),
            preserve_default=False,
        ),
    ]
