# Generated by Django 3.1.7 on 2021-03-26 08:26

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_apartment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='lat',
            field=models.FloatField(null=True, validators=[main.models.validate_lat], verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='building',
            name='lng',
            field=models.FloatField(null=True, validators=[main.models.validate_lng], verbose_name='Долгота'),
        ),
    ]
