# Generated by Django 3.1.7 on 2021-03-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210326_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='number',
            field=models.PositiveSmallIntegerField(verbose_name='Дом'),
        ),
    ]
