# Generated by Django 3.1.7 on 2021-03-26 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210326_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Населенный пункт')),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Улица')),
            ],
        ),
        migrations.RemoveField(
            model_name='building',
            name='city',
        ),
        migrations.AlterField(
            model_name='apartment',
            name='rooms',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Количество комнат'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='story',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Этаж'),
        ),
        migrations.AddField(
            model_name='building',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='main.location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='building',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='main.street', verbose_name='Улица'),
        ),
    ]
