# Generated by Django 3.1.7 on 2021-03-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210326_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='renovated',
            field=models.BooleanField(default=False, verbose_name='Ремонт'),
        ),
    ]
